### ISSUE TITLE
Update to alpine 3.17 for alpine based images

### ISSUE THREAD

**Issue by mervyn-mccreight** [bell-sw/Liberica#124]

**Comment by frankgrimes97** [comment]
It seems this was done as part of https://github.com/bell-sw/Liberica/pull/129 so it looks like this issue can now be closed.
However, it seems alpine 3.18 has now been released with some nice DNS resolution fixes:

> This release adds TCP fallback to the DNS stub resolver, fixing the longstanding inability to query large DNS records and incompatibility with recursive nameservers that don't give partial results in truncated UDP responses.

https://www.alpinelinux.org/posts/Alpine-3.18.0-released.html
https://gitlab.alpinelinux.org/alpine/tsc/-/issues/43

**Comment by pihug12** [comment]
It seems like the Liberica images are already based on Alpine 3.18 since May the 18th :
* https://hub.docker.com/r/bellsoft/liberica-openjdk-alpine-musl/tags?page=1&name=11.0.19
* https://hub.docker.com/r/bellsoft/liberica-openjre-alpine-musl/tags?page=1&name=11.0.19

There is no commit for this in the Git repository. :confused:
