### ISSUE TITLE
Why this JavaFX 23 Fix is not Included in JDK 23.

### ISSUE THREAD

**Issue by xulihang** [bell-sw/Liberica#191]
I just downloaded Liberica JDK 23 and found that this fix is not included in the JDK: https://github.com/openjdk/jfx/pull/1236

**Comment by voitylov** [comment]
It would be good to understand what has caused an impression that this fix is not included (as in, discuss the problem you observe). According to the release notes [1], source code [2], and test results, the fix is in.

[1] https://docs.bell-sw.com/liberica-jdk/23b38/general/release-notes/
[2] https://download.bell-sw.com/java/23+38/bellsoft-jdk23+38-src-full.tar.gz

**Comment by xulihang** [comment]
Well. The windows build does have this fix.

![image](https://github.com/user-attachments/assets/1900037e-6e57-4fde-a906-81710404d80c)

But it does not work as expected on macOS arm using a packaged version by javapackager.

Meanwhile, I encounter the following error directly running it on macOS x64:

```
java.lang.RuntimeException: java.lang.IllegalAccessException: class anywheresoftware.b4j.object.JavaObject cannot access class com.sun.javafx.collections.VetoableListDecorator (in module javafx.base) because module javafx.base does not export com.sun.javafx.collections to unnamed module @6f793049
```

I think I will keep using the builds by openjdk for now.

**Comment by voitylov** [comment]
While I'm not an expert with B4X, you may want to try to add #JavaCompilerPath to your app project attributes to make sure the app is compiled using JDK 23. Both your errors (on Mac M1 and x86_64) could easily be caused by not using the 23 javac (and/or not bundling the correct runtime with the app).

**Comment by xulihang** [comment]
This is not related to compilation. Even if I compile with JDK 11, as long as I use the JRE 23 with the fix, it works.

**Comment by voitylov** [comment]
Again, since I'm not an expert in B4X, it's hard to tell how the packaging of the runtime with the app is done. I just suggested to check that the runtime that is used to run the app is indeed 23. It's very easy to get confused by the compilation and packaging switches in various frameworks.

Anyway, here is a simple test https://github.com/openjdk/jfx/pull/1236#issuecomment-1732332755 that I used to check that the fix indeed works on Macs:
![ALIGN](https://github.com/user-attachments/assets/58b10faa-60a3-4278-a914-e4d11a9a1bc9)

To move this forward, please submit an isolated case similar to that that demonstrates the problem you are observing.

**Comment by xulihang** [comment]
Yes. This was my mistake. I have several JDKs installed:

```
$ ls /Library/Java/JavaVirtualMachines/
liberica-jdk-11-full.jdk	liberica-jdk-23-full.jdk
liberica-jdk-17-full.jdk	liberica-jdk-8-full.jdk
```

Then I used the following command to package it:

```bash
javapackager \
  -deploy -Bruntime=/Library/Java/JavaVirtualMachines/liberica-jdk-23-full.jdk/Contents/Home \
  -native image \
  -srcdir java \
  -srcfiles ImageTrans.jar \
  -outdir release \
  -outfile ImageTrans.jar \
  -appclass org.xulihang.imagetrans.main \
  -name ImageTrans \
  -title ImageTrans \
  -nosign \
  -v
```

But somehow, it still uses JDK 11 as the runtime.

So this issue can be closed as the fix is included.
