### ISSUE TITLE
Upgrade Alpine to fix CVE-2021-28831

### ISSUE THREAD

**Issue by fodil-a** [bell-sw/Liberica#56]
Hi,
All the OpenJDK Liberica Alpine images depend on version 3.13

This version contains BusyBox v1.32.1 and has CVE-2021-28831

Mitigating this CVE means upgrading the Alpine image to version 3.14, containing BusyBox v1.33.1, which mitigates this CVE

Do you accept PRs to fix this ?

Thanks !

**Comment by voitylov** [comment]
Thank you for the bug report!

Current OpenJDK Liberica Alpine images have Alpine version 3.13.5 as base. According to Alpine Linux documentation [1] and sources [2], CVE-2021-28831 was fixed in the previous version, 3.13.4. This version of Alpine has busybox 1.32.1-r4, which has the required patch.

It seems like some scanners have not properly updated their database [3]. This is a false positive, and the underlying issue is indeed not existent.

[1] https://alpinelinux.org/posts/Alpine-3.13.4-released.html
[2] https://gitlab.alpinelinux.org/alpine/aports/-/commit/7acc3190c16c19db5767c094d5ea6de75bbc2ae8
[3] https://github.com/alpinelinux/docker-alpine/issues/177
