### ISSUE TITLE
Urgent security update needed for all Java >=15 images

### ISSUE THREAD

**Issue by cfredri4** [bell-sw/Liberica#81]
As described here:
https://nakedsecurity.sophos.com/2022/04/20/critical-cryptographic-java-security-blunder-patched-update-now/

**Comment by marcphilipp** [comment]
According to this, 11.0.14 is also affected: https://www.oracle.com/security-alerts/cpuapr2022.html#AppendixJAVA

**Comment by voitylov** [comment]
I backported this fix to OpenJDK update releases. The website with Liberica JDK April release is live, linux repositories are being uploaded now, Docker images are next.

Please refer to the OpenJDK security advisory [1] and Liberica JDK update notes [2] for a list of releases where the fix is applicable. 

[1] https://openjdk.java.net/groups/vulnerability/advisories/2022-04-19
[2] https://bell-sw.com/announcements/2022/04/21/liberica-18-0-1-17-0-3-11-0-15-and-8u332-builds-are-generally-available/

**Comment by voitylov** [comment]
Updated images are now live.

**Comment by cfredri4** [comment]
@voitylov seems to be still using `17.0.2`?
https://github.com/bell-sw/Liberica/blob/1d3e4937c49478ce2a82e5335c19ce592aa814ba/docker/repos/liberica-openjre-alpine/17/Dockerfile#L55
